id: P007886
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4866
  title: མངོན་རྟོགས་རྒྱན་གྱི་སྤྱི་དོན་དང་འབྲུ་འགྲེལ།
  author: ''
  volumes:
    4fd58c4272014fe1b6fecd04b68a5993:
      image_group_id: I3CN4868
      title: ''
      volume_number: 1
      total_pages: 428
ebook_metadata:
  title: མངོན་རྟོགས་རྒྱན་གྱི་སྤྱི་དོན་དང་འབྲུ་འགྲེལ།
  author: ''
  sku: P007886
  cover: cover.jpg
  layers:
  - pagination
