id: I8762252B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:28:35+00:00'
last_modified: '2022-06-09T07:03:56.814110+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4866
  title: མངོན་རྟོགས་རྒྱན་གྱི་སྤྱི་དོན་དང་འབྲུ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C9BB:
      image_group_id: I3CN4868
      title: Volume 1 of shes rab kyi pha rol tu phyin pa mngon par rtogs pa'i rgyan
        gyi spyi don bdud rtsi'i nying khu dang 'bru 'grel yum don gsal ba'i sgron
        me/
      total_pages: 428
      order: 1
      base_file: C9BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
